#!/bin/sh

set -e

PLAYGROUND=$1

if [ ! -d $PLAYGROUND ]; then
  echo "Sorry, no $PLAYGROUND playground exists."
  exit 1
fi

cd $PLAYGROUND
vagrant up --provider=docker
vagrant ssh
vagrant destroy -f

